[package]
name = "rust"
version = "0.1.0"
authors = ["root"]

[dependencies]
fp-core = "0.1.9"
lazy_static = "1.4.0"
regex = "1.3.9"

[[bin]]
name = "step0_repl"
path = "step0_repl.rs"

[[bin]]
name = "step1_read_print"
path = "step1_read_print.rs"
